name: Deploy to Firebase Hosting
on:
  push:
    branches:
      - main  # Vérifie bien que ta branche s'appelle main et pas master
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_SNACKING_TEMPLATE }}"
          channelId: live
          projectId: snacking-template